[networks]
  ############# testnet-aws #############
  [networks.testnet-aws]
  hosts = [
      "http://18.167.142.95:26657",
      "http://18.167.77.79:26657",
      "http://18.167.136.23:26657",
      "http://18.166.232.162:26657",
      "http://18.167.133.255:26657",
      "http://18.166.181.170:26657",
      "http://18.163.54.130:26657",
      "http://18.167.164.175:26657",
      "http://18.166.240.67:26657",
      "http://18.162.176.55:26657",
  ]

  chain-id = "exchain-65"

  ############# testnet-ali #############
  [networks.testnet-ali]
  hosts = [
      "https://exchaintesttmrpc.okex.org",
  ]

  chain-id = "exchain-65"

  ############# mainnet-ali #############
  [networks.mainnet-ali]
  hosts = [
      "https://exchaintmrpc.okex.org",
  ]

  chain-id = "exchain-66"

  ############# local #############
  [networks.local]
  hosts = [
      "http://localhost:26657",
  ]

  chain-id = "exchainevm-8"

  ############# local-testnet #############
  [networks.local-testnet]
  hosts = [
      "http://localhost:10057",
  ]

  chain-id = "exchain-65"
