rewards_percentage = "0.8"

target_validator_addresses = [
    "okexchain18au05qx485u2qcw2gvqsrfh29evq77lm5stkf4",
    "okexchain1s6nfs7mlj7ewsskkrmekqhpq2w234fcz9sp3uz",
    "okexchain1zxthrcdcecfe5ss4tal0tq30hzel2lkstd3csd",
    "okexchain1q9nct2gska2yutx24starv6s63xz022fuzvv96",
    "okexchain195ez67wmhprwrru34gvttyd8ttpl7edxqd8rmt",
    "okexchain19wln93k3faq7vkqzlc9gljr3ey5fljt9q7gzhj",
    "okexchain1qva0ejf0t943x6rt824gwmvtjgec9cjrd84253",
    "okexchain1ka92ujcwh6hyyeu4tymzy3dedgxplt4d6uz6pp",
    "okexchain1zza3jrylyecrtuh0p9ts2xauzsefuvwaynydhs",
    "okexchain1ja9xngm4zh0t442mse73ll30p7dczd49ptxhds",
    "okexchain1c34s7lc7ec8gs9xrtxeh0j2wjaam25c3ermzx8",
    "okexchain1ygcvtcqxl82xvzrq25dymam434k3nnc88zd83d",
    "okexchain1m569cfenudxemegcf4mmykhugnslhdv0hmdu4v",
    "okexchain1fymxn4gazxzjdfvwvr0ccnrnjpwmj0r9azs0dj",
    "okexchain1xkl5agjzqnjnptyat2dng2asmx8g5kllej8eu6",
    "okexchain1tkwxgcpvptua0q0h5tn0at58ufnjdue7hdyksr",
]

worker_infos = [
    "okexchain1dtycve9dq2pgxx9nq5qlwp0wzk4atw82h95zy8,824",
    "okexchain1r0tpeugvrv8pp8yxsmfcratkpspuldvkunhfms,825",
    "okexchain1jquffu6lmx2phyzppnrj2kq2hdnhjaqd69xewd,826",
    "okexchain1c7spf0wmsxpyc43htr4xjx0reny8uz9r732s32,827",
    "okexchain18ewgu2g0dvks3j92pt7zxhy5h06hd4jz4wzaqs,828",
    "okexchain186mycru7jgcx4hrlktvcgpe74w7le8qt3va6sr,829",
    "okexchain1nl8zqt6tkq67m7jn2yx2wfh2l5jreayduf0w9j,830",
    "okexchain1y85tec3rh8jrej0afye8fgjk55u7wk8uu0s63k,831",
    "okexchain1zhwhtvscm0pnxvyu3c8xhf3x60qvm5n8jtfsfa,832",
    "okexchain1ah8cxa5wdumyfhc37p3x6f57yxdc5lapwpxe68,833",
    "okexchain13zzpce7pmm8fq9r2xxtd4g7x53cns5hkfqvuhv,834",
    "okexchain17shef6cxnyl693qspmukcc3223w7y0yx64u33c,835",
    "okexchain16qcgwr0t6en0u8vf3l55vyw0n37m5ntzt4tcph,836",
    "okexchain1q73c36c2sz0xzn58kglanp29ysjxeetghm3pt4,837",
    "okexchain1jqc4nuqm2fha82v4mpy0570e33zazawjnhtx2u,838",
    "okexchain1q6jen749qez0kwdyx3yv6yrrmnva9purkh2tty,839",
    "okexchain1cvf8ay2snns8tsjgv38l205thzpngzv2g4wjqs,840",
    "okexchain1qwrz6897mld5l3pwjdzqatp2zm2s4esxy5rvmy,841",
    "okexchain1naa5xn06r85fqzru8p86rsp84tx5lwjdtj9y5d,842",
    "okexchain1va25ew62xztnkzttepgywxkrv3e2hx95ddll6y,843",
    "okexchain1l50kutst6yyfnkzmemaqppd8042qzk54f4pqyy,844",
    "okexchain1ekhcpjw9zqw9xutdc473w5v79v0mgpj28qfd2f,845",
    "okexchain1yla0v54czq2fms30vajh4szxnshqqkd4vu95zw,846",
    "okexchain1my3w4gngacm2j9hla9z70wyc6h44nfhh6x82cw,847",
    "okexchain1eta7sw682qlgedyyva25h2ckj55jgsm4hpklcq,848",
    "okexchain1hapr0vyuvymzl7lv35ga7enwutwtwxl39mwugn,849",
    "okexchain1exs558ckwzwpjkeprdslrdc3r4000hyw8hr8ka,850",
    "okexchain1v7274jdlsz7pywcuxj2z9dpqfh7l63h8aqp67j,851",
    "okexchain1warldeh9tteu8mzcrm6e4w6hdr2xsq8jr3hp88,852",
    "okexchain1nylctcq5gav7j3l84e9qm8syxdmvc2xh0fsagx,853",
    "okexchain1qsrwelv79acepys967c444ahu6lxsnkzd7x98r,854",
    "okexchain1wjs02uklj9cr42rmjpszw52sf7sfzgv0yazl8k,855",
    "okexchain1pfqyvprwp7e9clpdf39h3z5qae4zdf5y75tvuw,856",
    "okexchain1xzegjkdjnk50cezxnhk2fk7463f3w9acgydpre,857",
    "okexchain14s60ulpg99anls0kf93g3839ch5py8f6whl3l5,858",
    "okexchain1jjc59t6myq0vezpvdefg9uu9y4u85h6rhl49v8,859",
    "okexchain15v0vlyltvkz4g9eju3ra2trmpppjafelshnnhm,860",
    "okexchain1astgw3x9gwr6fw3ufplz7ma2csar75zljsh9sl,861",
    "okexchain1fyykydf5xcgnrn8gj4ysvcalhpx2qm3qrk0fkq,862",
    "okexchain16un2qzpqxsmuzqdzgaej55245vpxmqfn8zvv2j,863",
    "okexchain1yt2rwpz4r0a3ntptvdp5kwhykm6mglkgeegm5m,864",
    "okexchain1uvd50jlxtlcwsct0sal39tnhufy89m4efjuxpe,865",
    "okexchain1dj3xwqd6yhpx2hffwgt02l2zrmn47fpl89jsey,866",
    "okexchain1ju4g5n7acmyx9ehtcvp6stytdgx96sc83x6wrh,867",
    "okexchain18gp3n084kqf76use0nqlga950m5l3e8r0g5tlj,868",
    "okexchain1w99s6axa03y3s0kct4e7pfu52mfk9jfv46fglu,869",
    "okexchain1c2ukw79907e7t8wa5emryp4skeqhsezngmn4mv,870",
    "okexchain1kjmappefrxgd79a3qwuv7770vxhl2svqd53amk,871",
    "okexchain18vun9yddwjpufyar00aehjwkq48lr4cd24lms5,872",
    "okexchain1fnagjc7jqlhagjafa8twhhraxx70xteqcdhgf9,873",
    "okexchain13745kcr7ljwkfsw8z0ac877y9kvwh0mmz95hp4,874",
    "okexchain1ws8y5x0uf25dmmsxr9y4pghacgj8uxeg7l8d2v,875",
    "okexchain1c2axdefh0qq5z7cc24sy4rpk00lzga73uk2xgc,876",
    "okexchain1r9z3nvcpq8tv8p4sxx8ea34kunhze8kdlyshyp,877",
    "okexchain19has2fh4cnue8fu80sda6rm955pvycy9rx7ert,878",
    "okexchain19xa3wuyxk3n4jsfqa776qkg0eeqnrl9mdnm8rq,879",
    "okexchain15g6l7ammmuuvlfvwazx9zfvl4e7t3r62zgseq3,880",
    "okexchain1fgyp8ayawmr80chg63wh76tyqlp4h0hgu7aeup,881",
    "okexchain1t4lndxwkkkz0ayg3yy0l9cdmmyrwhmpvwv84vk,882",
    "okexchain1ml2xszr6utypdeksh3fthecs3yncj0tnhvx6xr,883",
    "okexchain1x7w2tf9jk8dkja2hqtgfhskj6pycj7nswjaqzu,884",
    "okexchain1xemfhng202uwftef7rmeehhe5hjm7fn6lkqne3,885",
    "okexchain1jg9sucvmrqts3lh2wl0fh24ahu2gcfy9nwj4lj,886",
    "okexchain1vnhkhl4re2ftze8pz2t9hr7lx62dc8yf3axaph,887",
    "okexchain1hzca5ljwad00akmgq82cdhmre4kk9dkgyf6t6n,888",
    "okexchain1yx7mqjr9aywd72axchqwlaxnfk2rj3wwlt73tm,889",
    "okexchain1xtyn2uv9jwj4km537uv4m9gs3y3g83y2f93nlr,890",
    "okexchain1naualplvz9neex4c42yhzcrd36uzprvel33rkq,891",
    "okexchain1gtx36jn4j98p27hsv66tdeu4ce3ffalff3uja8,892",
    "okexchain1k2czxnr985h3fztk97c2f9qxux82vxk8ak3ruy,893",
    "okexchain190gvrtk6d5c95nj3rhcz9zcyuh9nmxnmh8q9aa,894",
    "okexchain15tlzj2rwq24hxwpgh3u9js2pevr0k6ee06y6aw,895",
    "okexchain10kxfngky5y3wd3gyfs3wyduyckucsdy82z9274,896",
    "okexchain12vwur75mre69sw7w05r48faw6eak0q64gtk0dw,897",
    "okexchain14rjxnzjpwlt5zfwmhh4u9cy2e9e5fm60w4jy2q,898",
    "okexchain14fx9p8nk5u25tzspjxdzc492ccz2jly2tf2c4p,899",
]