plundered_percentage = "0.9"

# all our validators
our_validator_addresses = [
    "okexchain18au05qx485u2qcw2gvqsrfh29evq77lm5stkf4",
    "okexchain1s6nfs7mlj7ewsskkrmekqhpq2w234fcz9sp3uz",
    "okexchain1zxthrcdcecfe5ss4tal0tq30hzel2lkstd3csd",
    "okexchain1q9nct2gska2yutx24starv6s63xz022fuzvv96",
    "okexchain195ez67wmhprwrru34gvttyd8ttpl7edxqd8rmt",
    "okexchain19wln93k3faq7vkqzlc9gljr3ey5fljt9q7gzhj",
    "okexchain1qva0ejf0t943x6rt824gwmvtjgec9cjrd84253",
    "okexchain1ka92ujcwh6hyyeu4tymzy3dedgxplt4d6uz6pp",
    "okexchain1zza3jrylyecrtuh0p9ts2xauzsefuvwaynydhs",
    "okexchain1ja9xngm4zh0t442mse73ll30p7dczd49ptxhds",
    "okexchain1c34s7lc7ec8gs9xrtxeh0j2wjaam25c3ermzx8",
    "okexchain1ygcvtcqxl82xvzrq25dymam434k3nnc88zd83d",
    "okexchain1m569cfenudxemegcf4mmykhugnslhdv0hmdu4v",
    "okexchain1fymxn4gazxzjdfvwvr0ccnrnjpwmj0r9azs0dj",
    "okexchain1xkl5agjzqnjnptyat2dng2asmx8g5kllej8eu6",
    "okexchain1tkwxgcpvptua0q0h5tn0at58ufnjdue7hdyksr",
    "okexchain1508d7eq592kg2lh9d46xvv3r4sm7gm8w7lza4q",
    "okexchain18v23ln9ycrtg0mrwsm004sh4tdknudtdvdedlk",
    "okexchain1ucmx6vvtrwam9pg20fnwmy9z80uhchyx3lm6fk",
    "okexchain1g3a6vtau2k93n4tqgqnrggeu3qa4x20reu5zjx",
    "okexchain19e6edpu97d6w2t5dlp7lph2fkdja0lvlrtjv3e",
    "okexchain1tat4lam8wjqmeax9mv4s584vu2mp7c0ceq7e4f",
    "okexchain1mlmwvdprn8dj6g45vdxkjsjgu4ntu9j7ulnjru",
    "okexchain1rz7frqz9ky52qqjwlpawfe5hz6plcrmmsmutxs",
    "okexchain1w3ptfgekjgdvwkqmdepdeyvuxqmcplfsnnr44d",
    "okexchain1v4kagglr3vq82vqywqd8quhsuarkm4kfmlrrn4",
    "okexchain1rmrx7wp60almzvghx2820aamjfd4kgwlf243dh",
    "okexchain13mayrjzsrp976y0ae0qw8sjan3qg2xfdgvxgup",
    "okexchain104y8sy0r6fke4a9qr8u05j6v5y68gkh4aaafza",
    "okexchain14zgafe7cynlpuhpfpqpxu2gntzhq6tteuvzcay",
    "okexchain1rv8tjxp8d8ucuak8c7svewwugzfdjwf9v0ncny",
]

# top 18 validators
our_top_18_addresses = [
    # Chillcrypto
    "okexchainvaloper1xkl5agjzqnjnptyat2dng2asmx8g5kllckhxqc",
    # Unique farming
    "okexchainvaloper1fymxn4gazxzjdfvwvr0ccnrnjpwmj0r9uxqs3s",
    # Tombolo
    "okexchainvaloper1m569cfenudxemegcf4mmykhugnslhdv0klarfw",
    # Defilego
    "okexchainvaloper1tkwxgcpvptua0q0h5tn0at58ufnjdue7kf5fvp",
    # Nodeplus
    "okexchainvaloper1ygcvtcqxl82xvzrq25dymam434k3nnc8xxacd0",
    # DeLab
    "okexchainvaloper1c34s7lc7ec8gs9xrtxeh0j2wjaam25c3c8ta69",
    # Hydrus
    "okexchainvaloper1508d7eq592kg2lh9d46xvv3r4sm7gm8wlmjzfz",
    # Blockpro
    "okexchainvaloper1ja9xngm4zh0t442mse73ll30p7dczd49q0kg3j",
    # ZK capitial
    "okexchainvaloper1zza3jrylyecrtuh0p9ts2xauzsefuvwa9h5jtj",
    # Samual
    "okexchainvaloper1ka92ujcwh6hyyeu4tymzy3dedgxplt4dmcj9ar",
    # Zapzap
    "okexchainvaloper1qva0ejf0t943x6rt824gwmvtjgec9cjrvr94gn",
    # Squares
    "okexchainvaloper19wln93k3faq7vkqzlc9gljr3ey5fljt9p6cats",
    # Nozash
    "okexchainvaloper195ez67wmhprwrru34gvttyd8ttpl7edxpfhu8f",
    # Collector
    "okexchainvaloper1q9nct2gska2yutx24starv6s63xz022faxunec",
    # Unicorn
    "okexchainvaloper1zxthrcdcecfe5ss4tal0tq30hzel2lks2fp8v0",
    # ChainHub
    "okexchainvaloper1s6nfs7mlj7ewsskkrmekqhpq2w234fczy53wqq",
    # Cryptomars
    "okexchainvaloper18au05qx485u2qcw2gvqsrfh29evq77lm45mf4h",
    # Validator4
    "okexchainvaloper19e6edpu97d6w2t5dlp7lph2fkdja0lvlz0zndm",
]

# 18 workers
workers_infos = [
    "okexchain1ra6urge6c8amyjk0pln2s3aefa7ak6sf2dqqku,806",
    "okexchain139kffxgctrnydhv5ahnx86mt2mkpcxcv4zry8x,807",
    "okexchain1637p2lzdfp48x4jvtmk6a4la6nmnp0v4vzlqv5,808",
    "okexchain1eyze64nqrjqxg40w7y5l8z2rah39hpx4d3ch5m,809",
    "okexchain1xs0ndkxultgldk2dvrf7dww0q4wku3t8uzu7zp,810",
    "okexchain1zua7exxn2wpdam6rlgrcgapv7fsjrct6770cwe,811",
    "okexchain1p50urkew76a6nk0s6r0falwc0jzznpxw2clz6h,812",
    "okexchain1gs90zkfql6jzj3zer06d3zmsdj0fuxx83qtuyf,813",
    "okexchain1en33je7g67t0eh2yswyzcrwjjsfwdpa9uhedjn,814",
    "okexchain16xqmjn3z36ues8hmhtvnrve9gm3gp760rgceqw,815",
    "okexchain1fvrt05h0chp37lkyy6zq4mayd6mflaahgk6333,816",
    "okexchain19eyu8zxlhuwy9rjsz8c36m4luu0dlaryz2cv4u,817",
    "okexchain134qfmgn0p5dpffxq57zdycaepl2mtpjdmcexq9,818",
    "okexchain1e0mr4vfjhxz30z6nx97nsd3z0a69vld0us6lv0,819",
    "okexchain1wgtgkzyzm3ecxntpqzzs2vr4rhqawlnpdld09k,820",
    "okexchain1uhph220d3mnhd2cgdgc8le0n6u654wsafufqem,821",
    "okexchain1zn3kd97jv385p27fnx3txp6j75exrq20pxkzuu,822",
    "okexchain1apl77v9q6eelphy067jkczuc78gckdgkzrc6gu,823",
    #    "okexchain1dtycve9dq2pgxx9nq5qlwp0wzk4atw82h95zy8,824",
    #    "okexchain1r0tpeugvrv8pp8yxsmfcratkpspuldvkunhfms,825",
    #    "okexchain1jquffu6lmx2phyzppnrj2kq2hdnhjaqd69xewd,826",
    #    "okexchain1c7spf0wmsxpyc43htr4xjx0reny8uz9r732s32,827",
    #    "okexchain18ewgu2g0dvks3j92pt7zxhy5h06hd4jz4wzaqs,828",
    #    "okexchain186mycru7jgcx4hrlktvcgpe74w7le8qt3va6sr,829",
    #    "okexchain1nl8zqt6tkq67m7jn2yx2wfh2l5jreayduf0w9j,830",
    #    "okexchain1y85tec3rh8jrej0afye8fgjk55u7wk8uu0s63k,831",
    #    "okexchain1zhwhtvscm0pnxvyu3c8xhf3x60qvm5n8jtfsfa,832",
    #    "okexchain1ah8cxa5wdumyfhc37p3x6f57yxdc5lapwpxe68,833",
    #    "okexchain13zzpce7pmm8fq9r2xxtd4g7x53cns5hkfqvuhv,834",
    #    "okexchain17shef6cxnyl693qspmukcc3223w7y0yx64u33c,835",
]